2020-06-19 13:26:42,221 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 258702ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 14:00:25,774 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 963348ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 18:19:26,328 ERROR 33873 [-/127.0.0.1/-/144ms POST /v2/essay] nodejs.ValidationError: Essay validation failed: title: Path `title` is required.
    at new ValidationError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/document.js:2554:32)
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/document.js:2376:17
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/schematype.js:1099:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
errors: {"title":{"message":"Path `title` is required.","name":"ValidatorError","properties":{"message":"Path `title` is required.","type":"required","path":"title"},"kind":"required","path":"title"}}
_message: "Essay validation failed"
message: "Essay validation failed: title: Path `title` is required."
name: "ValidationError"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 33873
hostname: MacBook-Pro.local

2020-06-19 19:33:22,303 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 3674741ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 21:00:16,401 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 1936637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 21:21:46,581 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 1246024ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 21:42:32,001 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 413997ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-19 22:47:19,405 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 3827383ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-20 02:14:12,666 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 7230794ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-20 09:29:12,911 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 26074696ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-20 11:56:59,399 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 126442ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 12:33:03,142 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 2123695ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 12:43:58,323 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 133504ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 15:17:38,222 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 8819810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 15:43:35,416 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 1057117ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 15:58:51,841 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 578984ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 16:07:56,594 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 64694ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 16:10:42,119 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 85507ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 19:31:24,569 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 11762398ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 23:50:43,338 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 2255756ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-20 23:53:29,956 ERROR 43974 nodejs.ClusterClientNoResponseError: client no response in 126548ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43974
hostname: MacBook-Pro.local

2020-06-21 02:58:41,632 ERROR 46496 nodejs.ClusterClientNoResponseError: client no response in 7251525ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 46496
hostname: MacBook-Pro.local

2020-06-21 08:33:50,396 ERROR 46496 nodejs.ClusterClientNoResponseError: client no response in 12521738ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 46496
hostname: MacBook-Pro.local

2020-06-21 09:04:55,004 ERROR 46496 nodejs.ClusterClientNoResponseError: client no response in 679378ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 46496
hostname: MacBook-Pro.local

2020-06-21 10:34:43,878 ERROR 48066 [-/127.0.0.1/-/18ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:34:53,375 ERROR 48066 [-/127.0.0.1/-/1ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:40:52,107 ERROR 48066 [-/127.0.0.1/-/1ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:45:03,599 ERROR 48066 [-/127.0.0.1/-/1ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:45:48,181 ERROR 48066 [-/127.0.0.1/-/2ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:46:07,590 ERROR 48066 [-/127.0.0.1/-/2ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 10:50:13,534 ERROR 48066 [-/127.0.0.1/-/1ms PUT /v2/essay/undefined] nodejs.CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "Essay"
    at new CastError (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4340:21)
    at model.Query.Query.then (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongoose@5.9.9@mongoose/lib/query.js:4432:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Cast to ObjectId failed for value \"undefined\" at path \"_id\" for model \"Essay\""
name: "CastError"
messageFormat: undefined
stringValue: "\"undefined\""
kind: undefined
value: "undefined"
path: "_id"
reason: {}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 48066
hostname: MacBook-Pro.local

2020-06-21 11:37:06,763 ERROR 47437 nodejs.ClusterClientNoResponseError: client no response in 2082516ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47437
hostname: MacBook-Pro.local

2020-06-21 11:49:47,250 ERROR 47437 nodejs.ClusterClientNoResponseError: client no response in 720495ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47437
hostname: MacBook-Pro.local

2020-06-21 13:23:29,515 ERROR 47437 nodejs.ClusterClientNoResponseError: client no response in 1981777ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47437
hostname: MacBook-Pro.local

2020-06-21 14:07:40,896 ERROR 47437 nodejs.ClusterClientNoResponseError: client no response in 2611399ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47437
hostname: MacBook-Pro.local

2020-06-21 20:45:30,203 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 647580ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

2020-06-21 20:50:19,428 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 289219ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

2020-06-21 22:19:55,380 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 1535302ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

2020-06-22 01:03:50,619 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 7154853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

2020-06-22 07:51:22,633 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 24407404ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

2020-06-22 10:18:53,202 ERROR 50391 nodejs.ClusterClientNoResponseError: client no response in 3250524ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 50391
hostname: MacBook-Pro.local

